server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
            uri: https://github.com/vKozik/calcBuilder-configs.git
      discovery:
        enabled: true

  jackson:
    serialization:
      INDENT_OUTPUT: true